version: "3.7"

volumes:
  local_db_data: {}

services:

  web:
    image: "memoryexpress/api:latest"
    env_file: .env
    build:
      context: .
      dockerfile: src/MemoryExpress.Web/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - PORT=5000,5001
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    depends_on:
      - postgres
    networks:
      - memoryexpress_api_network

  postgres:
    image: "postgres:11.4"
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - memoryexpress_api_network
    volumes:
      - local_db_data:/var/lib/postgresql/data

networks:
  memoryexpress_api_network:
    driver: bridge