version: 2

jobs:
 build:
   machine: true
   environment:
    ASPNETCORE_ENVIRONMENT: Production
    DOTNET_USE_POLLING_FILE_WATCHER: false
   steps:
     - checkout 

     # build image
     - run: |         
         docker info
         docker build -t memoryexpress/api:latest -f src/MemoryExpress.Web/prod.Dockerfile .
         # docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
         
     # deploy the image
     - run: |         
         docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
         docker tag memoryexpress/api:latest registry.heroku.com/$HEROKU_APP_NAME/web
         docker push registry.heroku.com/$HEROKU_APP_NAME/web                
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:release web -a $HEROKU_APP_NAME